### ISSUE TITLE
[Win/Cura 5.4] Crash when spamming the slice/cancel button.

### ISSUE THREAD

**Issue by rburema** [jellespijker/elevated_beats_n_slices#11]
I've it here as a screenshot, since this is one of those errors that kept throwing up new crash-reports every few milliseconds or so. (Trying to copy the text would've been a lot harder... Also, it's why it looks fuzzy, since the effects a new window opening up have are still playing.)

![2023-11-08 13_15_42-Window](https://github.com/jellespijker/elevated_beats_n_slices/assets/41987080/8fca385e-0887-4ef3-9223-37ec4063a1e8)

Like I say in the title, this happens when I spam the button, so I guess the player isn't recreated yet.

**Comment by jellespijker** [comment]
should be an easy enough fix, will create a patch release
