### ISSUE TITLE
FR: select music

### ISSUE THREAD

**Issue by rburema** [jellespijker/elevated_beats_n_slices#5]
For example, a list from https://incompetech.com/music/royalty-free/music.html (bonus: these tracks are used in nearly _every_ indie project / youtube video / etc. that doesn't have their own composer/musician -- so they're so overused that it also qualifies as muzak :-p )

**Comment by jellespijker** [comment]
Thanks, seems like a nice feature to add. Will add this to the 0.2 release planning

**Comment by jellespijker** [comment]
[farting_around.zip](https://github.com/jellespijker/elevated_beats_n_slices/files/13063350/farting_around.zip)

Also received the request to use this CC - licensed mp3, which would make the plugin more easily featured on youtube channels
