### ISSUE TITLE
Doesn't stop when cancel is pressed.

### ISSUE THREAD

**Issue by rburema** [jellespijker/elevated_beats_n_slices#6]
Obligatory: 'I've been a slicer developer for over 5 years now, and never encountered _any_ problems in slicing-related audio software.'

(Missed this when testing.)

Wanted to test with crashing models as well, but the 3 I opened all sliced in 5.5, so I'm running out of timebox here :-p

**Comment by jellespijker** [comment]
YOU FORGET TO USE ALL CAPS, WHICH I KNOWN YOU SHOULD USE WHEN YOU REPORT BUGS, BECAUSE I HAVE BEEN DEVELOPING SOFTWARE SINCE THE MS-DOS 3.x ERA!!!! ;-P 

But thanks for reporting this might to a patch release for this, since that would also allow me to change the extra `"` in the marketplace url.
